<?php

namespace Drupal\user_login\Plugin\Block;

use Drupal\Core\Block\BlockBase;

use Drupal\user\Entity\User;


/**
 * Provides a User Login block.
 *
 * @Block(
 *   id = "User_Login_block",
 *   admin_label = @Translation("User Login block"),
 * 
 * )
 */
class LoginInfo extends BlockBase {
  
// /**
//  * {@inheritdoc}
//  */

//retuns the output generated by populate_markup function 
 public function build() {
	return array(
    '#markup' => $this->_populate_markup(),
 );
}		
private function _populate_markup() {

  // Get current loged in user id and load user object	
  $user = User::load(\Drupal::currentUser()->id());

  // if user id <1 then its a guest user
  if ($user->get('uid')->value < 1) {

  //displays output with t().
    return t('Welcome Visitor! The current time is: ' . date('m-d-Y h:i:s', time()));

  } else {

  // $user_information .= 'User Name: ' . $user->getUsername() . "<br/>";
  $user_information .= 'Language: ' . $user->getPreferredLangcode() . "<br/>";
  $user_information .= 'Email: ' . $user->getEmail() . "<br/>";
  $user_information .= 'Timezone: ' . $user->getTimeZone() . "<br/>";
  $user_information .= 'Created: ' . date('m-d-Y h:i:s', $user->getCreatedTime()) . "<br/>";
  $user_information .= 'Updated: ' . date('m-d-Y h:i:s', $user->getChangedTime()) . "<br/>";
  $user_information .= 'Last Login: ' . date('m-d-Y h:i:s', $user->getLastLoginTime()) . "<br/>";
  $roles = NULL;

  foreach($user->getRoles() as $role) {
    
      $roles .= $role . ",";
      
  }
      
  $roles = 'Roles: ' . rtrim($roles, ',');
    
  $user_information .= $roles;

  //returns user information.
  return $user_information;
  }
  }
}